language: java

jdk:
- oraclejdk8

script: "mvn clean -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true -Dcobertura.report.format=xml --fail-at-end --batch-mode  package cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)